### ISSUE TITLE
OpenAL issue under Windows, help!

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#83]
In the v1.0.0.1-alpha release files, when using the sources directly in Windows using a fresh Eclipse, the following exception is raised:

```java
org.lwjgl.LWJGLException: Could not locate OpenAL library.
	at org.lwjgl.openal.AL.create(AL.java:151)
	at org.lwjgl.openal.AL.create(AL.java:102)
	at org.lwjgl.openal.AL.create(AL.java:201)
	at com.badlogic.gdx.backends.openal.OpenALAudio.<init>(OpenALAudio.java:70)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:80)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64)
	at hevs.gdx2d.lib.PortableApplication.createLwjglApplication(PortableApplication.java:317)
	at hevs.gdx2d.lib.PortableApplication.<init>(PortableApplication.java:72)
	at hevs.gdx2d.lib.PortableApplication.<init>(PortableApplication.java:84)
	at hevs.gdx2d.lib.PortableApplication.<init>(PortableApplication.java:94)
	at hevs.gdx2d.demos.simple.DemoCircles.<init>(DemoCircles.java:18)
	at hevs.gdx2d.demos.simple.DemoCircles.main(DemoCircles.java:27)
```

I saw that once in IntelliJ when I changed the project settings to UTF-8, I don't know if it is related. Do you also see that?

**Comment by RandomReaper** [comment]
Unfortunately, I'm unable to reproduce the bug. I have tested demos.music.*
Are you using audio in DemoCircles?

* eclipse-luna-sr2 java edition - 64 bit
* windows 7 64bit
* java 1.8.0_40

**Comment by pmudry** [comment]
This is odd : 

In IntelliJ with lwjgl logging setup (`System.setProperty("org.lwjgl.util.Debug","true");`) I get:

```
[LWJGL] getPathFromClassLoader: searching for: OpenAL32
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] getPathFromClassLoader: searching for: lwjgl
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] getPathFromClassLoader: searching for: lwjgl
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] Found 8 OpenAL paths
[LWJGL] Testing 'C:\Users\PIERRE~1\AppData\Local\Temp\libgdxPierre-André\1284024257\OpenAL64.dll'
[LWJGL] Found OpenAL at 'C:\Users\PIERRE~1\AppData\Local\Temp\libgdxPierre-André\1284024257\OpenAL64.dll'
```

In Eclipse

```
[LWJGL] getPathFromClassLoader: searching for: OpenAL32
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] getPathFromClassLoader: searching for: lwjgl
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] getPathFromClassLoader: searching for: lwjgl
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.net.URLClassLoader.findLibrary(java.lang.String)
[LWJGL] Failed to locate findLibrary method: java.lang.NoSuchMethodException: java.security.SecureClassLoader.findLibrary(java.lang.String)
[LWJGL] Found 44 OpenAL paths
[LWJGL] Testing 'C:\Users\PIERRE~1\AppData\Local\Temp\libgdxPierre-André\1284024257\OpenAL64.dll'
[LWJGL] Failed to load C:\Users\PIERRE~1\AppData\Local\Temp\libgdxPierre-André\1284024257\OpenAL64.dll: Could not load OpenAL library (126)
[LWJGL] Testing 'C:\Program Files\Java\jre1.8.0_40\bin\OpenAL64.dll'
[LWJGL] Failed to load C:\Program Files\Java\jre1.8.0_40\bin\OpenAL64.dll: Could not load OpenAL library (126)
[LWJGL] Testing 'C:\Windows\Sun\Java\bin\OpenAL64.dll'
[LWJGL] Failed to load C:\Windows\Sun\Java\bin\OpenAL64.dll: Could not load OpenAL library (126)
[LWJGL] Testing 'C:\Windows\system32\OpenAL64.dll'
[LWJGL] Failed to load C:\Windows\system32\OpenAL64.dll: Could not load OpenAL library (126)
[LWJGL] Testing 'C:\Windows\OpenAL64.dll'
[LWJGL] Failed to load C:\Windows\OpenAL64.dll: Could not load OpenAL library (126)
```

etc... 

Any idea, anyone?

**Comment by pmudry** [comment]
This seems to be related with accented names and the way libgdx creates temp directories for extracting natives libs. Let's hope others won't have that but I don't know how to fix this.

**Comment by metc** [comment]
```
[LWJGL] Testing 'OpenAL64.dll'
[LWJGL] Failed to load OpenAL64.dll: Could not load OpenAL library (126)
[LWJGL] Testing 'C:\Users\uadmin\AppData\Local\Temp\libgdxuadmin\1389850411\OpenAL32.dll'
[LWJGL] Found OpenAL at 'C:\Users\uadmin\AppData\Local\Temp\libgdxuadmin\1389850411\OpenAL32.dll'
```

Seams to work only thit the `OpenAL32.dll`. I cannot reproduce this bug. Works for me on Win7 x64.

**Comment by RandomReaper** [comment]
On 04/22/2015 09:38 AM, Pierre-André Mudry wrote:
> This seems to be related with accented names and the way libgdx creates temp directories for extracting natives libs. Let's hope others won't have that but I don't know how to fix this.
> 
accented names where ? in the windows user's name?

**Comment by pmudry** [comment]
I think so... In Windows 8 you can't really choose your username as it is
linked with some Microsoft online account

**Comment by RandomReaper** [comment]
Can you please change your name to 7-bit-ASCII :smile: ?

**Comment by pmudry** [comment]
Can't be reproduced easily. Hoping it won't come back since Libdx 1.5.6 update 3f6bf9efe22546161184c8b298d39a1e6854e6cb
