### ISSUE TITLE
Android support killed by libgdx update

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/gdx2d#84]
Every demo in the demoselector is crashing like that :

04-23 08:57:34.452: E/AndroidRuntime(12120): FATAL EXCEPTION: GLThread 62883
04-23 08:57:34.452: E/AndroidRuntime(12120): Process: hevs.androiddemoselector, PID: 12120
04-23 08:57:34.452: E/AndroidRuntime(12120): java.lang.NoSuchFieldError: com.badlogic.gdx.Gdx.gl
04-23 08:57:34.452: E/AndroidRuntime(12120): 	at com.badlogic.gdx.backends.android.AndroidGraphics.setupGL(AndroidGraphics.java:304)
04-23 08:57:34.452: E/AndroidRuntime(12120): 	at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:334)
04-23 08:57:34.452: E/AndroidRuntime(12120): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
04-23 08:57:34.452: E/AndroidRuntime(12120): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)

**Comment by RandomReaper** [comment]
Not working on desktop either...

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at hevs.gdx2d.components.graphics.Polygon.getEarClippedVertices(Polygon.java:59)
	at hevs.gdx2d.lib.GdxGraphics.drawFilledPolygon(GdxGraphics.java:800)
	at hevs.gdx2d.demos.simple.DemoSimpleShapes.onGraphicRender(DemoSimpleShapes.java:54)
	at hevs.gdx2d.lib.Game2D.render(Game2D.java:188)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by RandomReaper** [comment]
No luck with the desktop, it seems only "Simple shapes" is not working. But I can't find any working demo in android

**Comment by pmudry** [comment]
I had to change the polygon class to adapt to the new version of libgdx. It
think I have screwed up...

**Comment by RandomReaper** [comment]
Simple shape fixed (was polygon drawing problem)

**Comment by pmudry** [comment]
Fixed in 938b789bbdd96777d51f0451a33a112dc3f21973

**Comment by RandomReaper** [comment]
Nice, thank you :+1:
