### ISSUE TITLE
Status check in DR03

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#89]
Check that everything from RC1 works in DR03

**Comment by RandomReaper** [comment]
Demoselector not working in DR03 and not working on my computer (linux)

**Comment by metc** [comment]
@RandomReaper demos are launched only the first time ?

**Comment by metc** [comment]
This happens during the second launch, hope it's help:
```
java.lang.NullPointerException
	at org.lwjgl.opengl.LinuxContextImplementation.setSwapInterval(LinuxContextImplementation.java:146)
	at org.lwjgl.opengl.ContextGL.setSwapInterval(ContextGL.java:232)
	at org.lwjgl.opengl.DrawableGL.setSwapInterval(DrawableGL.java:86)
	at org.lwjgl.opengl.Display.setSwapInterval(Display.java:1129)
	at org.lwjgl.opengl.Display.setVSyncEnabled(Display.java:1142)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:446)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.initialize(LwjglCanvas.java:121)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.<init>(LwjglCanvas.java:70)
	at hevs.gdx2d.lib.gui.GdxDialog$1.<init>(Unknown Source)
	at hevs.gdx2d.lib.gui.GdxDialog.<init>(Unknown Source)
	at hevs.gdx2d.lib.gui.DemoSelectorGUI$TestList$RunButton$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
	at java.awt.EventQueue.access$400(EventQueue.java:81)
	at java.awt.EventQueue$2.run(EventQueue.java:633)
	at java.awt.EventQueue$2.run(EventQueue.java:631)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by metc** [comment]
See my PR https://github.com/LWJGL/lwjgl/pull/114

**Comment by pmudry** [comment]
Since f24abbf537dab2eeb991dceef1b3c316e25f5a51, there are still some exceptions but clicking twice make DemoSelector work also under Linux, at least on my Ubuntu.

Could you please check in DR03 ?

**Comment by pmudry** [comment]
@RandomReaper like a boss. Closing
